### ISSUE TITLE
Enable the updating of a mod description by a file ref

### ISSUE THREAD

**Issue by Lodrus** [Gwindalmir/SEWorkshopTool#27]
Currently, there appears to be no means of updating the description of a mod in the steam workshop. Could you please add a parameter to set the mod description in the workshop?

I'm not really familiar c#, but I think it's possible without much work. Keene's code appears to accept the mod description as a string: https://github.com/KeenSoftwareHouse/SpaceEngineers/blob/a109106fc0ded66bdd5da70e099646203c56550f/Sources/Sandbox.Game/Engine/Networking/MySteamWorkshop.cs#L266

If I understand the code correctly, then you just need to pass in the description here: https://github.com/Gwindalmir/SEWorkshopTool/blob/master/WorkshopToolCommon/Uploader.cs#L425

Ideally, I think the description should be passed in as a file reference relative to each mod directory. This would allow users to create and manage the mod description in my own git repo and simply upload it as a part of the mod itself. For example:
SEWorkshopTool --upload --mods . --description description.txt
where "description.txt" exists in "./some_mod/description.txt"

**Comment by Gwindalmir** [comment]
Thanks for the feedback.
I didn't implement this because I didn't see a use case, though I do like your idea of hosting the description in version control and submitting it with the update.
I'll see what I can do.
