### ISSUE TITLE
Support downloading mods to the DS directory

### ISSUE THREAD

**Issue by Gwindalmir** [Gwindalmir/SEWorkshopTool#3]
For server admins, it makes sense to batch download mods to the DS directory.
Ideally grab the right directory, but if not, allow passing a path on the command line.

**Comment by StarWeaver** [comment]
Oh hey, it's already here, cool. Doit. ;)

**Comment by Gwindalmir** [comment]
Keen moved workshop support to UGC, which pretty much makes this useless now.
However, in #15 I added an --appdata argument for specifying a custom location, which can extract mods anywhere.
