### ISSUE TITLE
--message prints file path to changelog instead of file contents

### ISSUE THREAD

**Issue by enenra** [Gwindalmir/SEWorkshopTool#38]
I just tried the --description and --message arguments for the first time. --description worked perfectly, but --message printed the file path of the file listed to the Steam changelog instead of the file contents.

**Comment by Gwindalmir** [comment]
What was the full command-line?
That will happen if it can't find the file you passed (i.e. relative path). There should also be some log lines.

**Comment by enenra** [comment]
```bat
set SEInstallDir="C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers"
for %%I in (.) do set ParentDirName=%%~nxI
%SEInstallDir%\Bin64\SEWorkshopTool.exe --upload --compile --mods "%ParentDirName%" --exclude .bat .psd .md --description description.md --message patch_notes.md
pause
```
with both description.md and patch_notes.md next to each other in the folder.

**Comment by Gwindalmir** [comment]
> 
> 
> ```batchfile
> set SEInstallDir="C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers"
> for %%I in (.) do set ParentDirName=%%~nxI
> %SEInstallDir%\Bin64\SEWorkshopTool.exe --upload --compile --mods "%ParentDirName%" --exclude .bat .psd .md --description description.md --message patch_notes.md
> pause
> ```
> 
> with both description.md and patch_notes.md next to each other in the folder.

Which folder? If the description, message, and thumbnail are relative, they are taken based on the directory you are in when you launch the program. They are _not_ relative to the mod folder.

I'm surprised description worked.
